import VideoEvents from '../Helpers/VideoEvents';
import VideoTimer from '../Helpers/VideoTimer';
import { IElement, Panel } from './BasicElements';
import * as Localization from '../Localization/Player';
export default class PlayerUI extends Panel {
    private id;
    protected events: VideoEvents;
    private board;
    private isPlaying;
    private reachedEnd;
    private currentTime;
    private controls;
    private timeline;
    private hidingButton;
    private videoDuration;
    Localization: Localization.Player;
    Timer: VideoTimer;
    private isBusy;
    constructor(id: string, events: VideoEvents);
    CreateControls(autohide: boolean): void;
    SetBusyText(text: string): void;
    private BindKeyboardShortcuts();
    AcceptCanvas(canvas: Element): void;
    private CreateBoard();
    private playPauseButton;
    private CreateButtonsPanel();
    private PlayPause();
    private JumpTo();
    private StartPlaying();
    private PausePlaying();
    private CreateTimeLine();
    private totalTime;
    private CreateTimeStatus();
    private ticking;
    private tickingInterval;
    UpdateCurrentTime(time?: number): void;
    ReachedEnd(): void;
    Busy(): void;
    Ready(): void;
    private volumeDownBtn;
    private volumeUpBtn;
    private volumeOffBtn;
    protected CreateAudioControls(): IElement;
    protected VolumeUp(): void;
    protected VolumeDown(): void;
    private isMuted;
    protected Mute(): void;
    protected ToggleAutohiding(): void;
}
